version: "3.9"
services:
  app:
    # container_name: peve-example
    build: .
    # restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    ports:
      - 3333:3333
